<?php

$curl = curl_init();
$channel =$_GET['c'];

$url="https://spapi.zee5.com/singlePlayback/getDetails/secure?channel_id=$channel&device_id=euqEbXxM2dHIyYg9E8zp000000000000&platform_name=mobile_web&translation=en&user_language=mr&country=IN&state=UP&app_version=3.15.17&user_type=premium&check_parental_control=false&uid=a72f20ea-6bd7-40fc-bc5a-da97aed4b637&ppid=euqEbXxM2dHIyYg9E8zp000000000000&version=12";

curl_setopt_array($curl, array(
  CURLOPT_URL => $url,
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS =>'{
  "x-access-token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF0Zm9ybV9jb2RlIjoiV2ViQCQhdDM4NzEyIiwiaXNzdWVkQXQiOiIyMDIzLTEyLTA2VDE4OjM1OjE5LjI0MVoiLCJwcm9kdWN0X2NvZGUiOiJ6ZWU1QDk3NSIsInR0bCI6ODY0MDAwMDAsImlhdCI6MTcwMTg4NzcxOX0.VUHzbaArXZyE5SnSvkOsVFRs83sEXMQhM5q2dyooaIE",  
  "Authorization": "eyJraWQiOiJlNmxfbGYweHpwYVk4VzBNcFQzWlBzN2hyOEZ4Y0trbDhDV0JaekVKT2lBIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiI5RTVCNDVCRS01MjMyLTRDRjEtOUUwMC02NDQ0REQyQjQxM0IiLCJzdWJzY3JpcHRpb25zIjoiW3tcImlkXCI6XCI1ZDA5NDIxNS1mMzBmLTExZWQtYjkyOC05OWI1ZmVhNGE0NzVcIixcInVzZXJfaWRcIjpcIjllNWI0NWJlLTUyMzItNGNmMS05ZTAwLTY0NDRkZDJiNDEzYlwiLFwiaWRlbnRpZmllclwiOlwiQ1JNXCIsXCJzdWJzY3JpcHRpb25fcGxhblwiOntcImlkXCI6XCIwLTExLTIwNzNcIixcImFzc2V0X3R5cGVcIjoxMSxcInN1YnNjcmlwdGlvbl9wbGFuX3R5cGVcIjpcIlNWT0RcIixcInRpdGxlXCI6XCJQcmVwYWlkIENvZGUgUGFjayAtIDEyIG1vbnRoc1wiLFwib3JpZ2luYWxfdGl0bGVcIjpcIlByZXBhaWQgQ29kZSBQYWNrIC0gMTIgbW9udGhzXCIsXCJzeXN0ZW1cIjpcIlo1XCIsXCJkZXNjcmlwdGlvblwiOlwiUHJlbWl1bSAtIDEyIG1vbnRocyAtIHByZXBhaWQgY29kZXNcIixcImJpbGxpbmdfY3ljbGVfdHlwZVwiOlwiZGF5c1wiLFwiYmlsbGluZ19mcmVxdWVuY3lcIjozNjUsXCJwcmljZVwiOjg5OSxcImN1cnJlbmN5XCI6XCJJTlJcIixcImNvdW50cmllc1wiOltcIklOXCJdLFwic3RhcnRcIjpcIjIwMjItMDMtMTRUMTc6MDQ6MDBaXCIsXCJlbmRcIjpcIjIwMjQtMTItMzFUMjM6NTk6MDBaXCIsXCJvbmx5X2F2YWlsYWJsZV93aXRoX3Byb21vdGlvblwiOmZhbHNlLFwicmVjdXJyaW5nXCI6ZmFsc2UsXCJwYXltZW50X3Byb3ZpZGVyc1wiOlt7XCJuYW1lXCI6XCJaZWU1XCIsXCJwcm9kdWN0X3JlZmVyZW5jZVwiOm51bGx9XSxcInByb21vdGlvbnNcIjpbXSxcImFzc2V0X3R5cGVzXCI6WzAsNiw5XSxcImFzc2V0X2lkc1wiOltcIlwiXSxcImZyZWVfdHJpYWxcIjowLFwiYnVzaW5lc3NfdHlwZVwiOlwiZnJlZVwiLFwiYmlsbGluZ190eXBlXCI6XCJwcmVtaXVtXCIsXCJudW1iZXJfb2Zfc3VwcG9ydGVkX2RldmljZXNcIjoyLFwibW92aWVfYXVkaW9fbGFuZ3VhZ2VzXCI6W10sXCJ0dl9zaG93X2F1ZGlvX2xhbmd1YWdlc1wiOltdLFwiY2hhbm5lbF9hdWRpb19sYW5ndWFnZXNcIjpbXSxcImR1cmF0aW9uX3RleHRcIjpcIlwiLFwidmFsaWRfZm9yX2FsbF9jb3VudHJpZXNcIjp0cnVlLFwiYWxsb3dlZF9wbGF5YmFja19kdXJhdGlvblwiOjYsXCJvZmZlcl9pZFwiOjAsXCJjYXRlZ29yeVwiOlwiXCIsXCJhY3R1YWxfdmFsdWVcIjowLFwiYmVmb3JlVHZcIjp0cnVlfSxcInN1YnNjcmlwdGlvbl9zdGFydFwiOlwiMjAyMy0wNS0xNVQxMDo1ODowMi4wMDBaXCIsXCJzdWJzY3JpcHRpb25fZW5kXCI6XCIyMDI0LTA1LTE0VDIzOjU5OjU5WlwiLFwic3RhdGVcIjpcImFjdGl2YXRlZFwiLFwicmVjdXJyaW5nX2VuYWJsZWRcIjpmYWxzZSxcInBheW1lbnRfcHJvdmlkZXJcIjpudWxsLFwiZnJlZV90cmlhbFwiOm51bGwsXCJjcmVhdGVfZGF0ZVwiOm51bGwsXCJpcF9hZGRyZXNzXCI6bnVsbCxcImNvdW50cnlcIjpcIklOXCIsXCJhZGRpdGlvbmFsXCI6e1wiY291bnRyeVwiOlwiSU5cIixcInBhcnRuZXJcIjpcIlpFRTVcIixcInN1YnNfdHlwZVwiOlwiaW50ZXJuYWxfc3Vic1wiLFwiY291cG9uY29kZVwiOlwiWjVQQkRFQ1lNUElQXCIsXCJpcF9hZGRyZXNzXCI6XCIyNDA5OjQwODE6MWMwMzo0ODAxOjQ3ODE6YmRlMDpmMWU6MzVlNywgMTg0Ljg2LjI0OC41NCwgMjMuNTIuNzMuMjQ0XCIsXCJwYXltZW50bW9kZVwiOlwiUHJlcGFpZENvZGVcIn0sXCJhbGxvd2VkX2JpbGxpbmdfY3ljbGVzXCI6MCxcInVzZWRfYmlsbGluZ19jeWNsZXNcIjowfV0iLCJhY3RpdmF0aW9uX2RhdGUiOiIyMDE5LTEyLTEzVDE5OjMxOjU2LjY3MFoiLCJhbXIiOlsiZGVsZWdhdGlvbiJdLCJpc3MiOiJodHRwczovL3VzZXJhcGkuemVlNS5jb20iLCJjdXJyZW50X2NvdW50cnkiOiJJTiIsImNsaWVudF9pZCI6InJlZnJlc2hfdG9rZW4iLCJhY2Nlc3NfdG9rZW5fdHlwZSI6IkRlZmF1bHRQcml2aWxlZ2UiLCJ1c2VyX3R5cGUiOiJSZWdpc3RlcmVkIiwidXNlcl9tb2JpbGUiOiI5MTkwNzU3OTc2NjQiLCJzY29wZSI6WyJ1c2VyYXBpIiwic3Vic2NyaXB0aW9uYXBpIiwicHJvZmlsZWFwaSJdLCJhdXRoX3RpbWUiOjE3MDE4ODI4MzAsImV4cCI6MTcwNDUxMjgzMCwiaWF0IjoxNzAxODgyODMwLCJqdGkiOiI4ZWY3N2E5My02YjgxLTRkMDAtYTBlNi1mNWRhMzczZGZlMjYiLCJkZXZpY2VfaWQiOiJhZGYwZmFmMi1hYWRjLTQwYTktODkwZC02ODE3ZDViOTQ1YTciLCJyZWdpc3RyYXRpb25fY291bnRyeSI6IklOIiwidmVyc2lvbiI6NSwiYXVkIjpbInVzZXJhcGkiLCJzdWJzY3JpcHRpb25hcGkiLCJwcm9maWxlYXBpIl0sInN5c3RlbSI6Ilo1IiwibmJmIjoxNzAxODgyODMwLCJpZHAiOiJsb2NhbCIsInVzZXJfaWQiOiI5ZTViNDViZS01MjMyLTRjZjEtOWUwMC02NDQ0ZGQyYjQxM2IiLCJjcmVhdGVkX2RhdGUiOiIyMDE5LTEyLTEzVDE5OjMxOjU2LjY3MFoiLCJhY3RpdmF0ZWQiOnRydWV9.3YWnwZ9P6SD-0RAJJWRiTKX08xJiRtG7tWamvAx4RoyTZAsso9LiGvMSWG_1qgAncqNlzIVnT9C88393FiQDlkWVY5TYeUZxjRFtMkV02jgwKuFfW1HqbiwGtG9P5KL4V4B9LijLCqQkAL0q-BujZtAZbMS4fRZE_68L3-IyrFK6cFSEmVnhOB6w9JjKeViMWPYQ3ilLM3y1H874ufYXQtKoso7Xs-fPr71y_QPLKDf9kOJIYOsa_Qoh73BNVEQIn5iKw2mSaR8l3PCheKIYD1_eMt4uSHCZy8HkVGgAt6ZaZUDzi2aRUQQjYDCndYL-ERBaSA6KtbMVd5v3cjwnEQ"
}',
  CURLOPT_HTTPHEADER => array(
    'Content-Type: application/json'
  ),
));


$response = curl_exec($curl);
curl_close($curl);

$zx = json_decode($response, true);
$image= $zx["assetDetails"]['image_url'];
$img = str_replace('270x152', '1170x658', $image);
$title= $zx["assetDetails"]['title'];
$des= $zx["assetDetails"]['description'];
$playit= $zx["keyOsDetails"]['video_token'];



header("Location: $playit");

?>